GET http://localhost:3001

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "username": "Carmelo@gmail.com",
    "password": "123"
}

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Carmelo@gmail.com",
    "password": "123"
}

GET http://localhost:3001/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzY0NDU0OTQ4LCJleHAiOjE3NjQ1NDEzNDh9.1p988GcEuY0O7EG8gIKVINV1wr68HU-J6gj4PnvTJnA
POST http://localhost:3001/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzY0NDU0OTQ4LCJleHAiOjE3NjQ1NDEzNDh9.1p988GcEuY0O7EG8gIKVINV1wr68HU-J6gj4PnvTJnA
Content-Type: application/json
{
    "task": "Clean Clothes"
}

PUT http://localhost:3001/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MjgxMjAyLCJleHAiOjE3NjQzNjc2MDJ9.GJIlsGusVcUYTVp1Xt0I0noA1hAqLpqt3XeR6-8ua8g
Content-Type: application/json
{
    "completed": 1
}

DELETE http://localhost:3001/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MjgxMjAyLCJleHAiOjE3NjQzNjc2MDJ9.GJIlsGusVcUYTVp1Xt0I0noA1hAqLpqt3XeR6-8ua8g
